name: Terraform Permission Alert

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  notify-permission-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Make script executable
        run: chmod +x .github/scripts/send-alert.sh

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          ./.github/scripts/send-alert.sh \
            "${{ steps.changed-files.outputs.all_changed_files }}" \
            "$GITHUB_REPOSITORY"